development: 
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['dev_db_database'] %>
  pool: 5
  username: <%= ENV['dev_db_username'] %>
  password: <%= ENV['dev_db_password'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: sllapp_test
  pool: 5
  username: sllapp
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sllapp
  username: rails
  password: psyche2279
  pool: 5
